name: VirtualHere Patcher

on:
  workflow_dispatch:
    inputs:
      serial_number:
        description: '输入序列号 (SN)'
        required: true
        default: 'aaabbbcccddd'
      device_count:
        description: '客户端数量'
        required: true
        default: '63'
      android_noroot:
        description: '安卓免root密钥获取'
        type: boolean
        required: false
        default: false

jobs:
  patch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        # 安装必要工具和库
        sudo apt-get update
        sudo apt-get install -y upx-ucl unzip
        
        # 安装 OpenSSL 1.1 兼容库
        echo "安装 OpenSSL 1.1 兼容库..."
        # 方法1: 尝试直接安装
        sudo apt-get install -y libssl1.1 2>/dev/null || true
        
        # 方法2: 如果上面失败，从Ubuntu 20.04源安装
        if ! ldconfig -p | grep libcrypto.so.1.1; then
          echo "从Ubuntu 20.04源安装 OpenSSL 1.1..."
          wget -q http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb 2>/dev/null || true
          rm -f libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        fi
        
        # 方法3: 如果还是不行，创建符号链接
        if ! ldconfig -p | grep libcrypto.so.1.1; then
          echo "创建 OpenSSL 符号链接..."
          sudo ln -sf /usr/lib/x86_64-linux-gnu/libcrypto.so.3 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 2>/dev/null || true
          sudo ln -sf /usr/lib/x86_64-linux-gnu/libssl.so.3 /usr/lib/x86_64-linux-gnu/libssl.so.1.1 2>/dev/null || true
          sudo ldconfig
        fi
        
        # 显示已安装的库
        echo "检查 OpenSSL 库："
        ldconfig -p | grep -E "libcrypto|libssl" || true
        
        # 解压activator
        echo "解压 activator2_linux.zip..."
        unzip -o activator2_linux.zip
        
        # 查看解压后的文件
        echo "解压后的文件："
        ls -la
        
        # 给activator添加执行权限
        if [ -f "activator" ]; then
          chmod +x activator
          echo "✓ activator 文件已设置执行权限"
        elif [ -f "activator2" ]; then
          chmod +x activator2
          mv activator2 activator
          echo "✓ activator2 文件已重命名并设置执行权限"
        else
          echo "查找所有可能的activator文件："
          find . -name "*activator*" -type f
        fi
        
        # 检查activator的依赖
        echo "检查 activator 依赖："
        ldd ./activator 2>&1 || echo "无法检查依赖"
        
        # 验证activator是否可执行
        if [ -x "./activator" ]; then
          echo "✓ activator 可执行"
          ./activator --help 2>&1 || echo "activator 无帮助信息（正常）"
        else
          echo "❌ activator 不可执行或不存在"
          exit 1
        fi
        
        # 创建输出目录
        mkdir -p patched_files
        mkdir -p licenses
        
    - name: Process VirtualHere files
      run: |
        # 处理ipk文件夹中的所有vhusbd文件
        for file in ipk/vhusbd*; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            echo "===== 处理文件: $filename ====="
            
            # 复制文件到工作目录
            cp "$file" "./$filename"
            
            # 尝试解压
            echo "尝试解压 $filename..."
            if upx -d "$filename" 2>/dev/null; then
              echo "✓ 解压成功"
              NEED_COMPRESS=true
            else
              echo "✗ 文件未压缩或解压失败，直接修补"
              NEED_COMPRESS=false
            fi
            
            # 修补文件
            echo "修补 $filename..."
            OUTPUT=$(./activator "$filename" "${{ github.event.inputs.serial_number }}" 2>&1) || true
            echo "$OUTPUT"
            
            # 提取License信息
            LICENSE=$(echo "$OUTPUT" | grep "License=" | cut -d'=' -f2-)
            if [ ! -z "$LICENSE" ]; then
              echo "$filename: $LICENSE" >> licenses/licenses.txt
              echo "License for $filename: $LICENSE"
            fi
            
            # 如果之前解压成功，则压缩
            if [ "$NEED_COMPRESS" = true ]; then
              echo "压缩 $filename..."
              upx -9 "$filename" 2>/dev/null || echo "压缩失败，保留未压缩版本"
            fi
            
            # 移动到输出目录
            mv "$filename" "patched_files/$filename"
            echo "✓ $filename 处理完成"
            echo ""
          fi
        done
        
    - name: Generate Android No-Root License
      if: ${{ github.event.inputs.android_noroot == 'true' }}
      run: |
        echo "===== 生成安卓免root密钥 ====="
        
        # 确认activator存在并可执行
        if [ ! -x "./activator" ]; then
          echo "❌ activator 不存在或不可执行"
          ls -la activator* 2>/dev/null || echo "没有找到activator文件"
          exit 1
        fi
        
        # 使用用户输入的序列号和设备数量
        SN="${{ github.event.inputs.serial_number }}"
        DEVICES="${{ github.event.inputs.device_count }}"
        
        echo "序列号: $SN"
        echo "设备数量: $DEVICES"
        
        # 设置 LD_LIBRARY_PATH 以防万一
        export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
        
        # 执行activator生成密钥
        echo "执行命令: ./activator xx $DEVICES $SN"
        OUTPUT=$(./activator xx "$DEVICES" "$SN" 2>&1) || true
        echo "$OUTPUT"
        
        # 提取License信息
        LICENSE=$(echo "$OUTPUT" | grep "License=" | cut -d'=' -f2-)
        if [ ! -z "$LICENSE" ]; then
          echo "Android No-Root License: $LICENSE" | tee -a licenses/android_noroot_license.txt
          echo "" >> licenses/android_noroot_license.txt
          echo "使用方法：" >> licenses/android_noroot_license.txt
          echo "在Windows客户端 USB服务器 - 许可证 - 输入密钥中输入: $LICENSE" >> licenses/android_noroot_license.txt
        else
          echo "⚠️ 未能提取License信息"
          echo "完整输出："
          echo "$OUTPUT"
        fi
        
    - name: Create summary
      run: |
        echo "# VirtualHere 修补完成报告" > patched_files/README.md
        echo "" >> patched_files/README.md
        echo "## 修补参数" >> patched_files/README.md
        echo "- 序列号: ${{ github.event.inputs.serial_number }}" >> patched_files/README.md
        echo "- 客户端数量: ${{ github.event.inputs.device_count }}" >> patched_files/README.md
        echo "- 安卓免root: ${{ github.event.inputs.android_noroot }}" >> patched_files/README.md
        echo "" >> patched_files/README.md
        
        echo "## 修补的文件" >> patched_files/README.md
        if ls patched_files/vhusbd* 1> /dev/null 2>&1; then
          for file in patched_files/vhusbd*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              filesize=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null || echo "unknown")
              echo "- $filename ($filesize bytes)" >> patched_files/README.md
            fi
          done
        else
          echo "- 无文件" >> patched_files/README.md
        fi
        echo "" >> patched_files/README.md
        
        if [ -f licenses/licenses.txt ]; then
          echo "## 生成的许可证" >> patched_files/README.md
          echo '```' >> patched_files/README.md
          cat licenses/licenses.txt >> patched_files/README.md
          echo '```' >> patched_files/README.md
        fi
        
        if [ -f licenses/android_noroot_license.txt ]; then
          echo "" >> patched_files/README.md
          echo "## Android免Root许可证" >> patched_files/README.md
          echo '```' >> patched_files/README.md
          cat licenses/android_noroot_license.txt >> patched_files/README.md
          echo '```' >> patched_files/README.md
        fi
        
        # 复制许可证文件到patched_files
        cp -r licenses/* patched_files/ 2>/dev/null || true
        
    - name: Upload patched files
      uses: actions/upload-artifact@v4
      with:
        name: virtualhere-patched-${{ github.event.inputs.serial_number }}
        path: patched_files/
        retention-days: 30
        
    - name: Display results
      run: |
        echo "===== 修补完成 ====="
        echo "修补的文件已上传到 Artifacts"
        echo ""
        if [ -f licenses/licenses.txt ]; then
          echo "生成的许可证："
          cat licenses/licenses.txt
        fi
        if [ -f licenses/android_noroot_license.txt ]; then
          echo ""
          echo "Android免Root许可证："
          cat licenses/android_noroot_license.txt
        fi
